### PR TITLE
check compatibility of `initial` and `param_info`

### LINKED ISSUE #59: Interaction between `initial` and `param_info` args for `tune_sim_anneal()`
The following situation came up in https://github.com/tidymodels/dials/issues/258

We make a grid with a wider range for a parameter (here mtry), use `tune_grid()` to get some initial tuning results, and then use them as the `initial` results to `tune_sim_anneal()`. 

However, we also give `tune_sim_anneal()` a parameter set for `param_info` - which has a _smaller_ range for that parameter than went into the initial tuning results. Then the transformation back and forth to [0,1] of that parameter breaks and dials throws an internal error that doesn't point directly to the actual problem.

I'm wondering if this is expected behavior or if it generally should work. If the error is to be expected, maybe we can catch that error more elegantly?

``` r
library(tidymodels)

set.seed(1)

rf_spec <- rand_forest(mode = "regression", mtry = tune())

grid_with_bigger_range <- grid_latin_hypercube(mtry(range = c(1, 16)))

car_folds <- vfold_cv(car_prices, v = 2)

car_wflow <- workflow() %>% 
  add_formula(Price ~ .) %>% 
  add_model(rf_spec)

tune_res_with_bigger_range <- tune_grid(
  car_wflow, 
  resamples = car_folds,
  grid = grid_with_bigger_range
)
parameter_set_with_smaller_range <- parameters(mtry(range = c(1, 5)))

finetune::tune_sim_anneal(
  car_wflow,
  param_info = parameter_set_with_smaller_range,
  resamples = car_folds,
  initial = tune_res_with_bigger_range,
  iter = 2
)
#> Optimizing rmse
#> Initial best: 2570.90000
#> Error in `.f()`:
#> ! Values should be on [0, 1].
#> ℹ This is an internal error that was detected in the dials package.
#>   Please report it at <https://github.com/tidymodels/dials/issues> with a reprex (<https://https://tidyverse.org/help/>) and the full backtrace.

#> Backtrace:
#>      ▆
#>   1. ├─finetune::tune_sim_anneal(...)
#>   2. ├─finetune:::tune_sim_anneal.workflow(...)
#>   3. │ └─finetune:::tune_sim_anneal_workflow(...)
#>   4. │   ├─... %>% ...
#>   5. │   └─finetune:::new_in_neighborhood(...)
#>   6. │     └─finetune:::random_integer_neighbor(...)
#>   7. │       └─finetune:::sample_by_distance(...)
#>   8. │         └─finetune:::encode_set_backwards(candidates, pset)
#>   9. │           └─purrr::map2(pset$object, x, dials::encode_unit, direction = "backward")
#>  10. │             ├─dials (local) .f(.x[[1L]], .y[[1L]], ...)
#>  11. │             └─dials:::encode_unit.quant_param(.x[[1L]], .y[[1L]], ...) at dials/R/encode_unit.R:23:2
#>  12. │               └─rlang::abort("Values should be on [0, 1].", .internal = TRUE) at dials/R/encode_unit.R:50:6
#>  13. └─dplyr::mutate(., .config = paste0("iter", i), .parent = current_parent)
#> ✖ Optimization stopped prematurely; returning current results.
#> # Tuning results
#> # 2-fold cross-validation 
#> # A tibble: 2 × 5
#>   splits            id    .metrics         .notes           .iter
#>   <list>            <chr> <list>           <list>           <int>
#> 1 <split [402/402]> Fold1 <tibble [6 × 5]> <tibble [0 × 3]>     0
#> 2 <split [402/402]> Fold2 <tibble [6 × 5]> <tibble [0 × 3]>     0
```

<sup>Created on 2022-11-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by simonpcouch**
Closes #59. This code just reproduces the portion of `dials::encode_unit()` methods that picks up on this discrepancy and gives it a more context-specific message.

``` r
library(tidymodels)

set.seed(1)

rf_spec <- rand_forest(mode = "regression", mtry = tune())

grid_with_bigger_range <- grid_latin_hypercube(mtry(range = c(1, 16)))

car_folds <- vfold_cv(car_prices, v = 2)

car_wflow <- workflow() %>% 
  add_formula(Price ~ .) %>% 
  add_model(rf_spec)

tune_res_with_bigger_range <- tune_grid(
  car_wflow, 
  resamples = car_folds,
  grid = grid_with_bigger_range
)
parameter_set_with_smaller_range <- parameters(mtry(range = c(1, 5)))

finetune::tune_sim_anneal(
  car_wflow,
  param_info = parameter_set_with_smaller_range,
  resamples = car_folds,
  initial = tune_res_with_bigger_range,
  iter = 2
)
#> Optimizing rmse
#> Initial best: 2570.90000
#> Error in `tune_sim_anneal()`:
#> ! The parameter set used when tuning generating the initial results
#>   isn't compatible with the parameter set supplied as `param_info`.
#> ℹ Possible values of parameters in `param_info` should encompass all values
#>   evaluated in the initial grid.
#>
#> ✖ Optimization stopped prematurely; returning current results.
#> # Tuning results
#> # 2-fold cross-validation 
#> # A tibble: 2 × 5
#>   splits            id    .metrics         .notes           .iter
#>   <list>            <chr> <list>           <list>           <int>
#> 1 <split [402/402]> Fold1 <tibble [6 × 5]> <tibble [0 × 3]>     0
#> 2 <split [402/402]> Fold2 <tibble [6 × 5]> <tibble [0 × 3]>     0
```

<sup>Created on 2024-01-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I've situated this solution so that it only applies to `tune_sim_anneal()` as `tune_bayes()` is able to handle that difference just fine.

### CODE REVIEW

File: R/sim_anneal_helpers.R [hunk 1]
```diff
@@ -144,11 +144,31 @@ random_real_neighbor <- function(current, hist_values, pset, retain = 1,
 
 encode_set_backwards <- function(x, pset, ...) {
   pset <- pset[pset$id %in% names(x), ]
-  new_vals <- purrr::map2(pset$object, x, dials::encode_unit, direction = "backward")
+  new_vals <- mapply(encode_unit_backwards, pset$object, x,
```
Comment (simonpcouch) [inline R/sim_anneal_helpers.R:147]: Transitioned to `mapply()` so that we don't get purrr's `Error in index i, caused by [call we can't control]` rethrown error formatting.

File: R/sim_anneal_helpers.R [hunk 2]
```diff
@@ -144,11 +144,31 @@ random_real_neighbor <- function(current, hist_values, pset, retain = 1,
...
+                     SIMPLIFY = FALSE, USE.NAMES = FALSE)
   names(new_vals) <- names(x)
   tibble::as_tibble(new_vals)
 }
 
+encode_unit_backwards <- function(x, value) {
```
Comment (topepo) [inline R/sim_anneal_helpers.R:153]: Can we call this something else, maybe starting with `check_`? 

When I first saw the name I thought it was only duplicating the functionality of `dials::encode_unit(x, value, direction = "backward")`

File: R/sim_anneal_helpers.R [hunk 3]
```diff
@@ -144,11 +144,31 @@ random_real_neighbor <- function(current, hist_values, pset, retain = 1,
...
+  if (!dials::has_unknowns(x)) {
+    compl <- value[!is.na(value)]
+    if (any(compl < 0) | any(compl > 1)) {
```
Comment (topepo) [inline R/sim_anneal_helpers.R:156]: Let's use this logical to tell them which parameter is triggering the error.

File: tests/testthat/test-sa-overall.R [hunk 4]
```diff
@@ -120,6 +120,56 @@ test_that("unfinalized parameters", {
...
+    dials::parameters(dials::mtry(range = c(1, 5)))
+
+  scrub_best <- function(lines) {
+    has_best <- grepl("Initial best", lines)
+    lines[has_best] <- ""
+    lines
+  }
+
+  set.seed(1)
+  expect_snapshot(error = TRUE, transform = scrub_best, {
```
Comment (topepo) [inline tests/testthat/test-sa-overall.R:161]: Nice! I didn't know about `transform`.

File: R/sim_anneal_helpers.R (hunk 3 above)
Comment (simonpcouch) [reply R/sim_anneal_helpers.R:157]: Ah, good thought. [245c6ff](https://github.com/tidymodels/finetune/pull/97/commits/245c6fff54a84f9b18d1b973d4eee7e933845b58)

File: R/sim_anneal_helpers.R (hunk 2 above)
Comment (simonpcouch) [reply R/sim_anneal_helpers.R]: [245c6ff](https://github.com/tidymodels/finetune/pull/97/commits/245c6fff54a84f9b18d1b973d4eee7e933845b58)

**Review by topepo — APPROVED** [review]
